### ISSUE TITLE
"Deepest one wins"

### ISSUE THREAD

**Issue by Neglexis** [tajo/react-titled#2]
Not sure what the difference is between the two examples.

**BASIC**
```js
<Titled title={() => 'Example.com'}>
  <h1>Welcome!</h1>
  <Titled title={title => `Homepage | ${title}`} />
</Titled>;
```

**DEEPEST ONE WINS**
```js
<Titled title={() => 'Example.com'}>
  <Titled title={() => 'Homepage'} />
</Titled>;
```

I notice the former has the `title` variable in the `title` props, but how would this work with triple nested titles?

**Comment by tajo** [comment]
Actually, there's no difference. I just wanted to make it really clear that this pattern works even if you want to overwrite upstream titles (the same way how react-document-title or react-helmet work, although they don't give you an option to compose from you parent).

> I notice the former has the title variable in the title props, but how would this work with triple nested titles?

The most inner nested will win. It's using `reduce()` to go through all title functions from top to bottom.

Maybe I should just delete the second example? Or enhance it somehow so it's not confusing?

**Comment by Neglexis** [comment]
But then what explains the difference in output?

> Homepage | Example.com

VS

> Homepage

**Comment by tajo** [comment]
```
<Titled title={title => `Homepage | ${title}`} />
```

vs

```
<Titled title={() => 'Homepage'} />
```

**Comment by Neglexis** [comment]
Not really clear what you're getting at..

How would you do triple nesting?

**Comment by tajo** [comment]
```js
<Titled title={() => 'Example.com'}>
  <h1>Welcome!</h1>
  <Titled title={title => `Homepage | ${title}`}>
    <Titled title={title => `Subpage | ${title}`} />
  </Titled>
</Titled>;
```

would produce

```
Subpage | Homepage | Example.com
```
