### ISSUE TITLE
Why `title` prop is forced to be a function?

### ISSUE THREAD

**Issue by OnkelTem** [tajo/react-titled#5]
I'm curious about the decision of making it a function. In my opinion it could be a plain variable most of time and only function it's really needed.  Titled component could have checked this and substitute () => props.title if it's not a function by its own.

**Comment by tajo** [comment]
> In my opinion it could be a plain variable most of time and only function it's really needed. 

Could be. However, even though this library is not strongly typed, it's nice to have unambiguous API types.

**Comment by OnkelTem** [comment]
nice for whom? :)
